version: "3.9"
# ref: https://docs.docker.com/compose/compose-file
services:
  app:
    image: nextjs-build-in-standalone-dev
    build:
      args:
        - target=dev
    environment:
      PORT: 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
